<a href="https://colab.research.google.com/github/Ashvasu14/2021-mlap/blob/main/Assignment__Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/Ashvasu14/MLA2021/main/Data/Car%20Price.csv' )
df.head( 10 )

   car_ID  symboling                   CarName  ... citympg highwaympg      price
0       1          3        alfa-romero giulia  ...      21         27  13495.000
1       2          3       alfa-romero stelvio  ...      21         27  16500.000
2       3          1  alfa-romero Quadrifoglio  ...      19         26  16500.000
3       4          2               audi 100 ls  ...      24         30  13950.000
4       5          2                audi 100ls  ...      18         22  17450.000
5       6          2                  audi fox  ...      19         25  15250.000
6       7          1                audi 100ls  ...      19         25  17710.000
7       8          1                 audi 5000  ...      19         25  18920.000
8       9          1                 audi 4000  ...      17         20  23875.000
9      10          0       audi 5000s (diesel)  ...      16         22  17859.167

[10 rows x 26 columns]

**More information about the dataset**

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   car_ID            205 non-null    int64
 1   symboling         205 non-null    int64
 2   CarName           205 non-null    object
 3   fueltype          205 non-null    object
 4   aspiration        205 non-null    object
 5   doornumber        205 non-null    object
 6   carbody           205 non-null    object
 7   drivewheel        205 non-null    object
 8   enginelocation    205 non-null    object
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64
 14  enginetype        205 non-null    object
 15  cylindernumber    205 non-null    object
 16  enginesize        205 non-null    int64
 17  fuelsystem        205 non-null    object
 18  boreratio         205 non-null    float64
 19  stroke            205 non-null    float64
 20  compressionratio  205 non-null    float64
 21  horsepower        205 non-null    int64
 22  peakrpm           205 non-null    int64
 23  citympg           205 non-null    int64
 24  highwaympg        205 non-null    int64
 25  price             205 non-null    float64
dtypes: float64(8), int64(8), object(10)
memory usage: 41.8+ KB

## **Creating Feature Set(X) and Outcome Variable(Y)**

In [5]:
Q1 = df.price.quantile(0.25)
Q3 = df.price.quantile(0.75)
Q1, Q3

(7788.0, 16503.0)

In [6]:
IQR = Q3 - Q1
IQR

8715.0

In [7]:
lower_limit = Q1 - 1.5*IQR
upper_limit = Q3 + 1.5*IQR
lower_limit, upper_limit

(-5284.5, 29575.5)

In [8]:
df[(df.price<lower_limit)|(df.price>upper_limit)]

     car_ID  symboling  ... highwaympg    price
15       16          0  ...         22  30760.0
16       17          0  ...         22  41315.0
17       18          0  ...         20  36880.0
47       48          0  ...         19  32250.0
48       49          0  ...         19  35550.0
49       50          0  ...         17  36000.0
70       71         -1  ...         25  31600.0
71       72         -1  ...         18  34184.0
72       73          3  ...         18  35056.0
73       74          0  ...         16  40960.0
74       75          1  ...         16  45400.0
126     127          3  ...         25  32528.0
127     128          3  ...         25  34028.0
128     129          3  ...         25  37028.0
129     130          1  ...         28  31400.5

[15 rows x 26 columns]

In [9]:
df_no_outlier = df[(df.price>lower_limit)&(df.price<upper_limit)]
df_no_outlier

     car_ID  symboling                   CarName  ... citympg highwaympg    price
0         1          3        alfa-romero giulia  ...      21         27  13495.0
1         2          3       alfa-romero stelvio  ...      21         27  16500.0
2         3          1  alfa-romero Quadrifoglio  ...      19         26  16500.0
3         4          2               audi 100 ls  ...      24         30  13950.0
4         5          2                audi 100ls  ...      18         22  17450.0
..      ...        ...                       ...  ...     ...        ...      ...
200     201         -1           volvo 145e (sw)  ...      23         28  16845.0
201     202         -1               volvo 144ea  ...      19         25  19045.0
202     203         -1               volvo 244dl  ...      18         23  21485.0
203     204         -1                 volvo 246  ...      26         27  22470.0
204     205         -1               volvo 264gl  ...      19         25  22625.0

[190 rows x 26 columns]

In [11]:
df.shape

(205, 26)

In [13]:
df_no_outlier.shape

(190, 26)

In [15]:
df['zscore'] = ( df_no_outlier.price - df_no_outlier.price.mean() ) / df_no_outlier.price.std()
df.zscore

0      0.399642
1      1.004459
2      1.004459
3      0.491220
4      1.195666
         ...
200    1.073897
201    1.516692
202    2.007791
203    2.206042
204    2.237239
Name: zscore, Length: 205, dtype: float64

In [19]:
df[df['zscore']>3]

    car_ID  symboling                   CarName  ... highwaympg    price    zscore
68      69         -1  buick century luxus (sw)  ...         25  28248.0  3.368982
69      70          0             buick century  ...         25  28176.0  3.354490

[2 rows x 27 columns]

In [20]:
df[df['zscore']<-3]

Empty DataFrame
Columns: [car_ID, symboling, CarName, fueltype, aspiration, doornumber, carbody, drivewheel, enginelocation, wheelbase, carlength, carwidth, carheight, curbweight, enginetype, cylindernumber, enginesize, fuelsystem, boreratio, stroke, compressionratio, horsepower, peakrpm, citympg, highwaympg, price, zscore]
Index: []

In [21]:
df[(df.zscore<-3) | (df.zscore>3)]

    car_ID  symboling                   CarName  ... highwaympg    price    zscore
68      69         -1  buick century luxus (sw)  ...         25  28248.0  3.368982
69      70          0             buick century  ...         25  28176.0  3.354490

[2 rows x 27 columns]

In [24]:
df_no_outliers = df[(df.zscore>-3) & (df.zscore<3)]

In [25]:
df.shape

(205, 27)

In [27]:
df_no_outliers.shape

(188, 27)